[v1]
"clippy 0.0.191 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-clippy", "clippy-driver"]
"https 1.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["http", "httplz"]
"racer 2.0.13 (registry+https://github.com/rust-lang/crates.io-index)" = ["racer"]
"rustfmt 0.10.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-fmt", "rustfmt"]
"wasm-gc 0.1.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-gc"]
