icons_format = "{icon}"

[theme]
theme = "native"

[icons]
icons = "awesome4"
# [icons.overrides]
# bat = " | | "
# bat_full = " |X| "
# bat_charging = " |^| "
# bat_discharging = " |v| "

[[block]]
block = "net"

[[block]]
block = "cpu"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %m-%d %H:%M:%S %z') "
timezone = "America/New_York"

[[block]]
block = "battery"
format = " $icon $percentage {$time |}"
