#!/usr/bin/env bash

current_branch=$(git rev-parse --abbrev-ref HEAD)

case ${current_branch} in
    master|develop|dev|trunk|main)
        echo "Blocked attempt to push to trunk. To override, use 'git push --no-verify'."
        exit 1
        ;;
    *)
       exit 0
esac

exit 0
