#!/bin/sh

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [[ $current_branch = 'master' ]]; then
  echo "Attempted push to master. Aborting. To override, use 'git push --no-verify'."
  exit 1
fi

exit 0

